#define HP_TRACERLED_PID 0x84FD
#define HP_TRACERLED_VID 0x103C

#define USB_BUF_ZONE_INDEX 0x36

enum {
    LED_ROTATION_STATIC = 0x01,
    LED_ROTATION_BREATHING = 0x06,
    LED_ROTATION_CYCLE = 0x07,
    LED_ROTATION_BLINKING = 0x08,
};

enum {
    LED_ZONE_LOGO = 0x01,
    LED_ZONE_BAR = 0x02,
    LED_ZONE_SOME_FAN = 0x03, // ??
    LED_ZONE_CPU = 0x04,
    LED_ZONE_FRONT_FAN_BOTTOM = 0x05,
    LED_ZONE_FRONT_FAN_TOP = 0x06,
};
